// Generated by carbonsteel. DO NOT EDIT.

package lmnt_test

import (
	"context"
	"testing"
)

func TestAccountGet(t *testing.T) {
	client := mockClient(`{}`)
	_, err := client.Account.Get(context.Background())
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}
