// Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths (tag: account)

package lmnt

import (
	"context"
	"net/http"
	"slices"

	"github.com/lmnt-com/lmnt-go/internal/apijson"
	"github.com/lmnt-com/lmnt-go/internal/requestconfig"
	"github.com/lmnt-com/lmnt-go/option"
	"github.com/lmnt-com/lmnt-go/packages/respjson"
)

// AccountService contains methods that help with interacting with the lmnt API.
//
// Note, unlike clients, this service does not read variables from the
// environment automatically. You should not instantiate this service directly,
// and instead use the [NewAccountService] method.
type AccountService struct {
	Options []option.RequestOption
}

// NewAccountService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewAccountService(opts ...option.RequestOption) (r AccountService) {
	r = AccountService{}
	r.Options = opts
	return
}

// Retrieve account
func (r *AccountService) Get(ctx context.Context, opts ...option.RequestOption) (res *AccountGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/account"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

type AccountGetResponse struct {
	Plan  AccountGetResponsePlan  `json:"plan" api:"required"`
	Usage AccountGetResponseUsage `json:"usage" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Plan        respjson.Field
		Usage       respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AccountGetResponse) RawJSON() string { return r.JSON.raw }
func (r *AccountGetResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type AccountGetResponsePlan struct {
	// The maximum number of characters per billing period allowed by your plan.
	CharacterLimit       int64 `json:"character_limit" api:"required"`
	CommercialUseAllowed bool  `json:"commercial_use_allowed" api:"required"`
	// The type of plan you are subscribed to.
	Type string `json:"type" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		CharacterLimit       respjson.Field
		CommercialUseAllowed respjson.Field
		Type                 respjson.Field
		ExtraFields          map[string]respjson.Field
		raw                  string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AccountGetResponsePlan) RawJSON() string { return r.JSON.raw }
func (r *AccountGetResponsePlan) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type AccountGetResponseUsage struct {
	// The number of characters remaining in this billing period.
	Characters int64 `json:"characters" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Characters  respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r AccountGetResponseUsage) RawJSON() string { return r.JSON.raw }
func (r *AccountGetResponseUsage) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
