// Generated by carbonsteel. DO NOT EDIT.

package lmnt

import (
	"github.com/lmnt-com/lmnt-go/v2/internal/apierror"
	"github.com/lmnt-com/lmnt-go/v2/packages/param"
	"github.com/lmnt-com/lmnt-go/v2/shared"
)

// paramObj is aliased to make [param.APIObject] private when embedded in
// generated request params structs.
type paramObj = param.APIObject

// Error is the error type returned for non-2xx API responses.
type Error = apierror.Error

// ErrorType is the slug identifying an API error category.
type ErrorType = shared.ErrorType

// Equals "invalid_request_error"
const ErrorTypeInvalidRequestError = shared.ErrorTypeInvalidRequestError

// Equals "authentication_error"
const ErrorTypeAuthenticationError = shared.ErrorTypeAuthenticationError

// Equals "permission_error"
const ErrorTypePermissionError = shared.ErrorTypePermissionError

// Equals "not_found_error"
const ErrorTypeNotFoundError = shared.ErrorTypeNotFoundError

// Equals "payment_required_error"
const ErrorTypePaymentRequiredError = shared.ErrorTypePaymentRequiredError

// Equals "rate_limit_error"
const ErrorTypeRateLimitError = shared.ErrorTypeRateLimitError

// Equals "internal_server_error"
const ErrorTypeInternalServerError = shared.ErrorTypeInternalServerError

// LanguageCode is an alias to [shared.LanguageCode].
type LanguageCode = shared.LanguageCode

const (
	LanguageCodeAuto = shared.LanguageCodeAuto
	LanguageCodeAr   = shared.LanguageCodeAr
	LanguageCodeAs   = shared.LanguageCodeAs
	LanguageCodeBn   = shared.LanguageCodeBn
	LanguageCodeCs   = shared.LanguageCodeCs
	LanguageCodeDa   = shared.LanguageCodeDa
	LanguageCodeDe   = shared.LanguageCodeDe
	LanguageCodeEn   = shared.LanguageCodeEn
	LanguageCodeEs   = shared.LanguageCodeEs
	LanguageCodeFi   = shared.LanguageCodeFi
	LanguageCodeFr   = shared.LanguageCodeFr
	LanguageCodeHi   = shared.LanguageCodeHi
	LanguageCodeID   = shared.LanguageCodeID
	LanguageCodeIt   = shared.LanguageCodeIt
	LanguageCodeJa   = shared.LanguageCodeJa
	LanguageCodeKo   = shared.LanguageCodeKo
	LanguageCodeMl   = shared.LanguageCodeMl
	LanguageCodeMr   = shared.LanguageCodeMr
	LanguageCodeNl   = shared.LanguageCodeNl
	LanguageCodePl   = shared.LanguageCodePl
	LanguageCodePt   = shared.LanguageCodePt
	LanguageCodeRu   = shared.LanguageCodeRu
	LanguageCodeSk   = shared.LanguageCodeSk
	LanguageCodeSv   = shared.LanguageCodeSv
	LanguageCodeTa   = shared.LanguageCodeTa
	LanguageCodeTe   = shared.LanguageCodeTe
	LanguageCodeTh   = shared.LanguageCodeTh
	LanguageCodeTr   = shared.LanguageCodeTr
	LanguageCodeUk   = shared.LanguageCodeUk
	LanguageCodeUr   = shared.LanguageCodeUr
	LanguageCodeVi   = shared.LanguageCodeVi
	LanguageCodeZh   = shared.LanguageCodeZh
)

// Model is an alias to [shared.Model].
type Model = shared.Model

const (
	ModelBlizzard = shared.ModelBlizzard
)

// OutputFormat is an alias to [shared.OutputFormat].
type OutputFormat = shared.OutputFormat

const (
	OutputFormatAAC      = shared.OutputFormatAAC
	OutputFormatMP3      = shared.OutputFormatMP3
	OutputFormatULaw     = shared.OutputFormatULaw
	OutputFormatWav      = shared.OutputFormatWav
	OutputFormatWebM     = shared.OutputFormatWebM
	OutputFormatPCMS16LE = shared.OutputFormatPCMS16LE
	OutputFormatPCMF32LE = shared.OutputFormatPCMF32LE
)

// SampleRate is an alias to [shared.SampleRate].
type SampleRate = shared.SampleRate

const (
	SampleRate8000  = shared.SampleRate8000
	SampleRate16000 = shared.SampleRate16000
	SampleRate24000 = shared.SampleRate24000
)
