// Generated by carbonsteel. DO NOT EDIT.

package lmnt_test

import (
	"testing"

	"go.uber.org/goleak"
)

// TestMain runs the suite under goleak so a leaked keepalive or reader
// goroutine fails the build rather than passing silently. Idle HTTP
// keep-alive connections pooled by the Prism-backed REST tests aren't
// leaks, so their transport goroutines are ignored.
func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m,
		goleak.IgnoreAnyFunction("net/http.(*persistConn).readLoop"),
		goleak.IgnoreAnyFunction("net/http.(*persistConn).writeLoop"),
	)
}
