// Generated by carbonsteel. DO NOT EDIT.

package lmnt

import (
	"os"

	"github.com/lmnt-com/lmnt-go/option"
)

// Client creates a struct with services and top level methods that help with
// interacting with the lmnt API. You should not instantiate this client directly,
// and instead use the [NewClient] method.
type Client struct {
	Options []option.RequestOption
	Speech  SpeechService
	Voice   VoiceService
	Account AccountService
}

// DefaultClientOptions reads from the environment (LMNT_API_KEY, LMNT_BASE_URL)
// and returns the options applied before any caller-supplied options.
func DefaultClientOptions() []option.RequestOption {
	defaults := []option.RequestOption{
		option.WithHTTPClient(defaultHTTPClient()),
		option.WithBaseURL("https://api.lmnt.com"),
	}
	if o, ok := os.LookupEnv("LMNT_BASE_URL"); ok {
		defaults = append(defaults, option.WithBaseURL(o))
	}
	if o, ok := os.LookupEnv("LMNT_API_KEY"); ok {
		defaults = append(defaults, option.WithAPIKey(o))
	}
	return defaults
}

// NewClient generates a new client with the default options read from the
// environment. Options passed in as arguments are applied after the defaults,
// and all options propagate to the services and requests this client makes.
//
// Pass [option.WithoutEnvironmentDefaults] to skip the environment-based
// credential autoload entirely.
func NewClient(opts ...option.RequestOption) (r Client) {
	var defaults []option.RequestOption
	if option.HasWithoutEnvironmentDefaults(opts) {
		defaults = []option.RequestOption{
			option.WithHTTPClient(defaultHTTPClient()),
			option.WithBaseURL("https://api.lmnt.com"),
		}
	} else {
		defaults = DefaultClientOptions()
	}
	opts = append(defaults, opts...)

	r = Client{Options: opts}
	r.Speech = NewSpeechService(opts...)
	r.Voice = NewVoiceService(opts...)
	r.Account = NewAccountService(opts...)

	return
}
