// Generated by carbonsteel. DO NOT EDIT. Source: asyncapi.yaml#/operations

package lmnt

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"iter"
	"slices"
	"sync"
	"sync/atomic"
	"time"

	"github.com/lmnt-com/lmnt-go/internal"
	"github.com/lmnt-com/lmnt-go/internal/apijson"
	"github.com/lmnt-com/lmnt-go/internal/requestconfig"
	"github.com/lmnt-com/lmnt-go/option"
	"github.com/lmnt-com/lmnt-go/packages/respjson"
	"github.com/lmnt-com/lmnt-go/packages/wsstream"
	"github.com/tidwall/gjson"
)

const speechSessionPath = "/v1/ai/speech/stream"

// defaultWSKeepAlive is the WebSocket keepalive ping interval used when the caller
// does not override it with option.WithWSKeepAlive.
const defaultWSKeepAlive = 30 * time.Second

// ErrSessionClosed is the sentinel returned by the Send methods (and by Recv) once
// the session has been closed locally. Check it with errors.Is.
var ErrSessionClosed = errors.New("lmnt speech session: closed")

// SessionService is the WebSocket speech-session resource, reached via the parent
// service (e.g. client.Speech.Sessions).
type SessionService struct {
	Options []option.RequestOption
}

// NewSessionService generates a new session service that applies the given options to
// each session it opens.
func NewSessionService(opts ...option.RequestOption) (r SessionService) {
	r = SessionService{}
	r.Options = opts
	return
}

// SessionNewParams configures a new speech session.
type SessionNewParams struct {
	// The voice ID to use for speech generation, obtained from 'List voices' API
	Voice string
	// The desired output format of the audio.
	// - `mp3`: 96kbps MP3 audio.
	// - `pcm_s16le`: PCM signed 16-bit little-endian audio.
	// - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
	// - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
	// - `webm`: WebM format with Opus audio codec.
	Format   SessionInitFormat
	Language LanguageCode
	// Controls whether the server will return timestamps for the generated speech
	ReturnTimestamps bool
	// The desired output audio sample rate
	SampleRate SessionInitSampleRate
}

// The desired output format of the audio.
// - `mp3`: 96kbps MP3 audio.
// - `pcm_s16le`: PCM signed 16-bit little-endian audio.
// - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
// - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
// - `webm`: WebM format with Opus audio codec.
type SessionInitFormat string

const (
	SessionInitFormatMP3      SessionInitFormat = "mp3"
	SessionInitFormatPCMS16LE SessionInitFormat = "pcm_s16le"
	SessionInitFormatPCMF32LE SessionInitFormat = "pcm_f32le"
	SessionInitFormatULaw     SessionInitFormat = "ulaw"
	SessionInitFormatWebM     SessionInitFormat = "webm"
)

// The desired output audio sample rate
type SessionInitSampleRate int64

const (
	SessionInitSampleRate24000 SessionInitSampleRate = 24000
	SessionInitSampleRate16000 SessionInitSampleRate = 16000
	SessionInitSampleRate8000  SessionInitSampleRate = 8000
)

// sessionInit is the wire shape of the init frame. Internal; marshaled with stdlib
// encoding/json — an all-required discriminated message, no Opt semantics needed.
type sessionInit struct {
	Type             string `json:"type"`
	APIKey           string `json:"X-API-Key"`
	LmntVersion      string `json:"lmnt-version"`
	Voice            string `json:"voice"`
	Format           string `json:"format,omitempty"`
	Language         string `json:"language,omitempty"`
	ReturnTimestamps bool   `json:"return_timestamps,omitempty"`
	SampleRate       int64  `json:"sample_rate,omitempty"`
}

// New opens a speech session: it dials the WebSocket (blocking only on the
// transport-level upgrade), writes the init frame, and returns. It does NOT block
// on the server's `ready` frame — that arrives via Recv and populates RequestID, so
// the Send methods may be called immediately.
func (r *SessionService) New(ctx context.Context, params SessionNewParams, opts ...option.RequestOption) (*SpeechSession, error) {
	opts = slices.Concat(r.Options, opts)
	cfg, err := requestconfig.SessionConfig(ctx, opts...)
	if err != nil {
		return nil, err
	}
	wsURL, err := speechSessionURL(cfg)
	if err != nil {
		return nil, err
	}
	dial := cfg.WSDialer
	if dial == nil {
		dial = wsstream.Dial
	}
	conn, err := dial(ctx, wsURL, cfg.Request.Header.Clone())
	if err != nil {
		return nil, err
	}

	frame, err := json.Marshal(sessionInit{
		Type:             "init",
		APIKey:           cfg.APIKey,
		LmntVersion:      internal.APIVersion,
		Voice:            params.Voice,
		Format:           string(params.Format),
		Language:         string(params.Language),
		ReturnTimestamps: params.ReturnTimestamps,
		SampleRate:       int64(params.SampleRate),
	})
	if err != nil {
		conn.Close()
		return nil, err
	}
	if err := conn.Write(ctx, wsstream.MessageText, frame); err != nil {
		conn.Close()
		return nil, fmt.Errorf("lmnt speech session: send init: %w", err)
	}

	readCtx, cancel := context.WithCancel(context.Background())
	sess := &SpeechSession{conn: conn, readCtx: readCtx, cancel: cancel}

	keepAlive := cfg.WSKeepAlive
	if keepAlive == 0 {
		keepAlive = defaultWSKeepAlive
	}
	if keepAlive > 0 {
		go func() {
			ticker := time.NewTicker(keepAlive)
			defer ticker.Stop()
			for {
				select {
				case <-ticker.C:
					_ = sess.conn.Ping(sess.readCtx)
				case <-sess.readCtx.Done():
					return
				}
			}
		}()
	}
	return sess, nil
}

// speechSessionURL composes the wss:// session URL from the configured base URL,
// rewriting the scheme and replacing the path with the channel address.
func speechSessionURL(cfg *requestconfig.RequestConfig) (string, error) {
	base := cfg.BaseURL
	if base == nil {
		base = cfg.DefaultBaseURL
	}
	if base == nil {
		return "", errors.New("lmnt speech session: no base URL configured")
	}
	u := *base
	if u.Scheme == "http" || u.Scheme == "ws" {
		u.Scheme = "ws"
	} else {
		u.Scheme = "wss"
	}
	u.Path = speechSessionPath
	u.RawQuery = ""
	return u.String(), nil
}

// SpeechSession is a bidirectional speech-streaming session. The Send methods are safe to
// call from any goroutine; Recv, Messages, and StreamAudio are single-reader. Close
// is idempotent. This is the gRPC bidirectional-stream contract.
type SpeechSession struct {
	conn      wsstream.Conn
	readCtx   context.Context
	cancel    context.CancelFunc
	requestID atomic.Pointer[string]
	nextNonce atomic.Int64
	closeOnce sync.Once
	closeErr  error
}

// RequestID returns the per-session request id once the server's `ready` frame has
// been received and consumed via Recv. Returns "" before then. Safe for concurrent use.
func (s *SpeechSession) RequestID() string {
	if p := s.requestID.Load(); p != nil {
		return *p
	}
	return ""
}

// Send text to the server to append into the text stream.
//
// The text you send can be split at any point. For example, sending `This is a
// test of the emergency broadcast system` is semantically equivalent to sending
// `This is a test of the eme` and `rgency broadcast system` separately.
func (s *SpeechSession) SendText(ctx context.Context, text string) error {
	return s.send(ctx, "send text", map[string]any{"text": text, "type": "text"})
}

// Force the server to generate speech for all buffered text in the stream.
//
// The server replies with a `flush_complete` carrying a matching `nonce` once it
// has finished streaming the flushed audio.
//
// <Warning>
// Be careful when using `flush`. Our models are designed to factor in context when
// generating speech. When flushing the buffer at arbitrary points, your speech may
// sound less natural.
// </Warning>
//
// The returned nonce is echoed back by the matching acknowledgement.
func (s *SpeechSession) SendFlush(ctx context.Context) (nonce int64, err error) {
	nonce = s.nextNonce.Add(1)
	if err := s.send(ctx, "send flush", map[string]any{"nonce": nonce, "type": "flush"}); err != nil {
		return 0, err
	}
	return nonce, nil
}

// Drop the server's buffered text without generating speech for it.
//
// The server replies with a `reset_complete` carrying the matching `nonce` once
// the buffer has been cleared.
//
// You do not need to wait for `reset_complete` to begin sending more text.
//
// The returned nonce is echoed back by the matching acknowledgement.
func (s *SpeechSession) SendReset(ctx context.Context) (nonce int64, err error) {
	nonce = s.nextNonce.Add(1)
	if err := s.send(ctx, "send reset", map[string]any{"nonce": nonce, "type": "reset"}); err != nil {
		return 0, err
	}
	return nonce, nil
}

// Inform the server you're done appending text to this session and want it to
// close when the server has finished dispatching speech.
func (s *SpeechSession) SendFinish(ctx context.Context) error {
	return s.send(ctx, "send finish", map[string]any{"type": "finish"})
}

func (s *SpeechSession) send(ctx context.Context, what string, msg map[string]any) error {
	if s.readCtx.Err() != nil {
		return fmt.Errorf("lmnt speech session: %s: %w", what, ErrSessionClosed)
	}
	payload, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("lmnt speech session: %s: %w", what, err)
	}
	if err := s.conn.Write(ctx, wsstream.MessageText, payload); err != nil {
		return fmt.Errorf("lmnt speech session: %s: %w", what, err)
	}
	return nil
}

// Recv returns the next message from the server. Single-reader: do not call it
// concurrently with itself, Messages, or StreamAudio. Returns io.EOF on a graceful
// close (by Close or by the server).
func (s *SpeechSession) Recv(ctx context.Context) (SpeechSessionMessage, error) {
	if s.readCtx.Err() != nil {
		return nil, io.EOF
	}
	readCtx := s.readCtx
	if d, ok := ctx.Deadline(); ok {
		dc, cancel := context.WithDeadline(s.readCtx, d)
		defer cancel()
		readCtx = dc
	}
	frame, err := s.conn.Read(readCtx)
	if err != nil {
		if s.readCtx.Err() != nil || errors.Is(err, io.EOF) {
			return nil, io.EOF
		}
		return nil, err
	}
	return s.decode(frame)
}

// Messages is the Go 1.23 range-over-func form of Recv. Iteration ends cleanly on a
// graceful close; a non-EOF error is yielded once and then ends iteration.
func (s *SpeechSession) Messages(ctx context.Context) iter.Seq2[SpeechSessionMessage, error] {
	return func(yield func(SpeechSessionMessage, error) bool) {
		for {
			msg, err := s.Recv(ctx)
			if errors.Is(err, io.EOF) {
				return
			}
			if !yield(msg, err) {
				return
			}
			if err != nil {
				return
			}
		}
	}
}

// StreamAudio drains audio frames to w until the session closes cleanly (returning
// nil) or the server sends an error frame (returned as a wrapped error). Non-audio,
// non-error frames are skipped.
func (s *SpeechSession) StreamAudio(ctx context.Context, w io.Writer) error {
	for {
		msg, err := s.Recv(ctx)
		if errors.Is(err, io.EOF) {
			return nil
		}
		if err != nil {
			return err
		}
		switch m := msg.(type) {
		case *SpeechSessionAudio:
			if _, err := w.Write(m.Data); err != nil {
				return err
			}
		case *SpeechSessionError:
			return m
		}
	}
}

// Close shuts the session down. It is idempotent: the first call closes the
// connection and cancels the reader; later calls return the same result.
func (s *SpeechSession) Close() error {
	s.closeOnce.Do(func() {
		s.cancel()
		s.closeErr = s.conn.Close()
	})
	return s.closeErr
}

func (s *SpeechSession) decode(frame wsstream.Frame) (SpeechSessionMessage, error) {
	if frame.Kind == wsstream.MessageBinary {
		return &SpeechSessionAudio{Data: append([]byte(nil), frame.Data...)}, nil
	}
	msgType := gjson.GetBytes(frame.Data, "type").String()
	switch msgType {
	case "ready":
		var m SpeechSessionReady
		if err := apijson.UnmarshalRoot(frame.Data, &m); err != nil {
			return nil, err
		}
		requestID := m.RequestID
		s.requestID.Store(&requestID)
		return &m, nil
	case "timestamps":
		var m SpeechSessionTimestamps
		if err := apijson.UnmarshalRoot(frame.Data, &m); err != nil {
			return nil, err
		}
		return &m, nil
	case "flush_complete":
		var m SpeechSessionFlushComplete
		if err := apijson.UnmarshalRoot(frame.Data, &m); err != nil {
			return nil, err
		}
		return &m, nil
	case "reset_complete":
		var m SpeechSessionResetComplete
		if err := apijson.UnmarshalRoot(frame.Data, &m); err != nil {
			return nil, err
		}
		return &m, nil
	case "error":
		var m SpeechSessionError
		if err := apijson.UnmarshalRoot(frame.Data, &m); err != nil {
			return nil, err
		}
		return &m, nil
	default:
		return nil, fmt.Errorf("lmnt speech session: unknown message type %q", msgType)
	}
}

// SpeechSessionMessage is the sealed receive-side union. Type-switch on it after Recv.
type SpeechSessionMessage interface {
	isSpeechSessionMessage()
}

// First message sent by the server, confirming the session is established.
type SpeechSessionReady struct {
	// Per-session request ID. If you're reporting an issue, include this if possible
	// to make debugging easier.
	RequestID string `json:"request_id" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		RequestID   respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SpeechSessionReady) RawJSON() string { return r.JSON.raw }
func (r *SpeechSessionReady) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

func (*SpeechSessionReady) isSpeechSessionMessage() {}

// Binary audio data returned from the server.
type SpeechSessionAudio struct {
	// Data is a copy of the frame bytes, safe to retain.
	Data []byte
}

func (*SpeechSessionAudio) isSpeechSessionMessage() {}

// Timestamps for the audio chunk that was just streamed, if requested in `init`.
type SpeechSessionTimestamps struct {
	// Array of timestamp objects, one per generated text token.
	//
	// <Warning>
	// The timestamps array resets its start time for each chunk of audio.
	// </Warning>
	Timestamps []Timestamp `json:"timestamps"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Timestamps  respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SpeechSessionTimestamps) RawJSON() string { return r.JSON.raw }
func (r *SpeechSessionTimestamps) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

func (*SpeechSessionTimestamps) isSpeechSessionMessage() {}

// Acknowledgement that a flush command has been completed.
//
// The `nonce` matches the one carried by the original flush, allowing you to
// determine when it has completed.
type SpeechSessionFlushComplete struct {
	// The nonce that was carried by the original `flush`.
	Nonce int64 `json:"nonce" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Nonce       respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SpeechSessionFlushComplete) RawJSON() string { return r.JSON.raw }
func (r *SpeechSessionFlushComplete) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

func (*SpeechSessionFlushComplete) isSpeechSessionMessage() {}

// Acknowledgement that a reset command has been completed.
//
// The `nonce` matches the one carried by the original reset, allowing you to
// discard any remaining in-flight speech before the reset.
type SpeechSessionResetComplete struct {
	// The nonce that was carried by the original `reset`.
	Nonce int64 `json:"nonce" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Nonce       respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SpeechSessionResetComplete) RawJSON() string { return r.JSON.raw }
func (r *SpeechSessionResetComplete) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

func (*SpeechSessionResetComplete) isSpeechSessionMessage() {}

// Error envelope returned by the server. Connection closes immediately afterward.
type SpeechSessionError struct {
	Detail ErrorBody `json:"error" api:"required"`
	// Per-session request ID. If you're reporting an issue, include this if possible
	// to make debugging easier.
	RequestID string `json:"request_id" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Detail      respjson.Field
		RequestID   respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SpeechSessionError) RawJSON() string { return r.JSON.raw }
func (r *SpeechSessionError) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

func (*SpeechSessionError) isSpeechSessionMessage() {}

type Timestamp struct {
	// The text segment
	Text string `json:"text" api:"required"`
	// The time at which the text starts, in seconds
	Start float64 `json:"start" api:"required"`
	// The spoken duration of the text segment, in seconds
	Duration float64 `json:"duration" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Text        respjson.Field
		Start       respjson.Field
		Duration    respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r Timestamp) RawJSON() string { return r.JSON.raw }
func (r *Timestamp) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ErrorBody struct {
	// Slug identifying the error category.
	Type ErrorType `json:"type" api:"required"`
	// Human-readable error message.
	Message string `json:"message" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Type        respjson.Field
		Message     respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r ErrorBody) RawJSON() string { return r.JSON.raw }
func (r *ErrorBody) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Error implements the error interface so SpeechSessionError composes with errors.Is /
// errors.As and can be returned directly by StreamAudio.
func (e *SpeechSessionError) Error() string {
	return fmt.Sprintf("lmnt speech session: %s: %s", e.Detail.Type, e.Detail.Message)
}

// Type returns the API error category, for parity with apierror.Error.Type().
func (e *SpeechSessionError) Type() ErrorType { return e.Detail.Type }

var (
	_ SpeechSessionMessage = (*SpeechSessionReady)(nil)
	_ SpeechSessionMessage = (*SpeechSessionAudio)(nil)
	_ SpeechSessionMessage = (*SpeechSessionTimestamps)(nil)
	_ SpeechSessionMessage = (*SpeechSessionFlushComplete)(nil)
	_ SpeechSessionMessage = (*SpeechSessionResetComplete)(nil)
	_ SpeechSessionMessage = (*SpeechSessionError)(nil)
	_ error                = (*SpeechSessionError)(nil)
)
