// Generated by carbonsteel. DO NOT EDIT.

package lmnt_test

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"sync"
	"testing"

	lmnt "github.com/lmnt-com/lmnt-go"
	"github.com/lmnt-com/lmnt-go/option"
	"github.com/lmnt-com/lmnt-go/packages/wsstream"
)

// fakeConn is an in-process wsstream.Conn: it replays a scripted list of frames
// and records every write.
type fakeConn struct {
	mu     sync.Mutex
	toRead []wsstream.Frame
	writes [][]byte
	closed bool
}

func (c *fakeConn) Write(_ context.Context, _ wsstream.MessageKind, payload []byte) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.writes = append(c.writes, append([]byte(nil), payload...))
	return nil
}

func (c *fakeConn) Read(ctx context.Context) (wsstream.Frame, error) {
	c.mu.Lock()
	if len(c.toRead) > 0 {
		f := c.toRead[0]
		c.toRead = c.toRead[1:]
		c.mu.Unlock()
		return f, nil
	}
	c.mu.Unlock()
	<-ctx.Done()
	return wsstream.Frame{}, ctx.Err()
}

func (c *fakeConn) Ping(context.Context) error { return nil }

func (c *fakeConn) Close() error {
	c.mu.Lock()
	c.closed = true
	c.mu.Unlock()
	return nil
}

func fakeSession(t *testing.T, frames []wsstream.Frame) (*lmnt.SpeechSession, *fakeConn) {
	t.Helper()
	conn := &fakeConn{toRead: frames}
	client := lmnt.NewClient(
		option.WithAPIKey("test"),
		option.WithWSKeepAlive(-1),
		option.WithWSDialer(func(context.Context, string, http.Header) (wsstream.Conn, error) {
			return conn, nil
		}),
	)
	sess, err := client.Speech.Sessions.New(context.Background(), lmnt.SessionNewParams{Voice: "leah"})
	if err != nil {
		t.Fatalf("New: %s", err)
	}
	return sess, conn
}

func TestSpeechSessionHappyPath(t *testing.T) {
	sess, conn := fakeSession(t, []wsstream.Frame{
		{Kind: wsstream.MessageText, Data: []byte(`{"type":"ready","request_id":"req_1"}`)},
		{Kind: wsstream.MessageBinary, Data: []byte("audiobytes")},
	})
	defer sess.Close()

	// New writes the init frame synchronously; it must carry the API version.
	conn.mu.Lock()
	initFrame := conn.writes[0]
	conn.mu.Unlock()
	var initMsg map[string]any
	if err := json.Unmarshal(initFrame, &initMsg); err != nil {
		t.Fatalf("init frame is not JSON: %s", err)
	}
	if initMsg["lmnt-version"] != "1.1" {
		t.Fatalf("init lmnt-version: got %v, want 1.1", initMsg["lmnt-version"])
	}

	if err := sess.SendText(context.Background(), "hello"); err != nil {
		t.Fatalf("SendText: %s", err)
	}

	m1, err := sess.Recv(context.Background())
	if err != nil {
		t.Fatalf("Recv ready: %s", err)
	}
	ready, ok := m1.(*lmnt.SpeechSessionReady)
	if !ok {
		t.Fatalf("expected *SpeechSessionReady, got %T", m1)
	}
	if ready.RequestID != "req_1" {
		t.Fatalf("request id: got %q", ready.RequestID)
	}
	if sess.RequestID() != "req_1" {
		t.Fatalf("session RequestID(): got %q", sess.RequestID())
	}

	m2, err := sess.Recv(context.Background())
	if err != nil {
		t.Fatalf("Recv audio: %s", err)
	}
	audio, ok := m2.(*lmnt.SpeechSessionAudio)
	if !ok {
		t.Fatalf("expected *SpeechSessionAudio, got %T", m2)
	}
	if string(audio.Data) != "audiobytes" {
		t.Fatalf("audio data: got %q", audio.Data)
	}
}

func TestSpeechSessionSendAfterClose(t *testing.T) {
	sess, _ := fakeSession(t, nil)
	if err := sess.Close(); err != nil {
		t.Fatalf("Close: %s", err)
	}
	err := sess.SendText(context.Background(), "late")
	if !errors.Is(err, lmnt.ErrSessionClosed) {
		t.Fatalf("expected ErrSessionClosed, got %v", err)
	}
}
