// Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths (tag: speech)

package lmnt

import (
	"context"
	"net/http"
	"slices"

	"github.com/lmnt-com/lmnt-go/internal/apijson"
	"github.com/lmnt-com/lmnt-go/internal/requestconfig"
	"github.com/lmnt-com/lmnt-go/option"
	"github.com/lmnt-com/lmnt-go/packages/param"
	"github.com/lmnt-com/lmnt-go/packages/respjson"
)

// SpeechService contains methods that help with interacting with the lmnt API.
//
// Note, unlike clients, this service does not read variables from the
// environment automatically. You should not instantiate this service directly,
// and instead use the [NewSpeechService] method.
type SpeechService struct {
	Options  []option.RequestOption
	Sessions SessionService
}

// NewSpeechService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewSpeechService(opts ...option.RequestOption) (r SpeechService) {
	r = SpeechService{}
	r.Options = opts
	r.Sessions = NewSessionService(opts...)
	return
}

// Generate speech
func (r *SpeechService) Generate(ctx context.Context, body SpeechGenerateParams, opts ...option.RequestOption) (res *http.Response, err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append(opts, option.WithResponseInto(&res))
	path := "v1/ai/speech/bytes"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, nil, opts...)
	return
}

// Generate speech with timestamps
func (r *SpeechService) GenerateDetailed(ctx context.Context, body SpeechGenerateDetailedParams, opts ...option.RequestOption) (res *SpeechGenerateDetailedResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/ai/speech"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

type SpeechGenerateDetailedResponse struct {
	// The base64-encoded audio file; the format is determined by the `format`
	// parameter.
	Audio string `json:"audio" api:"required"`
	// An array describing where each generated input element (words and non-words like
	// spaces, punctuation, etc.) falls in the audio.
	Timestamps []TimestampObject `json:"timestamps"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Audio       respjson.Field
		Timestamps  respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r SpeechGenerateDetailedResponse) RawJSON() string { return r.JSON.raw }
func (r *SpeechGenerateDetailedResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type TimestampObject struct {
	// The spoken duration of the generated input element, in seconds.
	Duration float64 `json:"duration" api:"required"`
	// The start time of the generated input element, in seconds.
	Start float64 `json:"start" api:"required"`
	// The generated input element; beginning and ending with a short silence.
	Text string `json:"text" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Duration    respjson.Field
		Start       respjson.Field
		Text        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r TimestampObject) RawJSON() string { return r.JSON.raw }
func (r *TimestampObject) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SpeechGenerateParams struct {
	// The text to generate speech from; max 5000 characters per request (including
	// spaces).
	Text string `json:"text" api:"required"`
	// The voice id of the voice to use; voice ids can be retrieved by calls to `List
	// voices` or `Voice info`.
	Voice string `json:"voice" api:"required"`
	// When set to true, the generated speech will also be saved to your [clip
	// library](https://app.lmnt.com/clips) in the LMNT playground.
	Debug param.Opt[bool] `json:"debug,omitzero"`
	// The desired output format of the audio. If you are using a streaming endpoint,
	// you'll generate audio faster by selecting a streamable format since chunks are
	// encoded and returned as they're generated. For non-streamable formats, all
	// speech will be generated before encoding.
	//
	// Streamable formats:
	// - `mp3`: 96kbps MP3 audio.
	// - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
	// - `webm`: WebM format with Opus audio codec.
	// - `pcm_s16le`: PCM signed 16-bit little-endian audio.
	// - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
	//
	// Non-streamable formats:
	// - `aac`: AAC audio codec.
	// - `wav`: 16-bit PCM audio in WAV container.
	Format OutputFormat `json:"format,omitzero"`
	// The desired language. Two letter ISO 639-1 code. Defaults to auto language
	// detection, but specifying the language is recommended for faster generation.
	Language LanguageCode `json:"language,omitzero"`
	// The model to use for speech generation. Learn more about models
	// [here](https://docs.lmnt.com/models/overview).
	Model Model `json:"model,omitzero"`
	// The desired output sample rate in Hz. Defaults to `24000` for all formats except
	// `mulaw` which defaults to `8000`.
	SampleRate SampleRate `json:"sample_rate,omitzero"`
	// Influences how expressive and emotionally varied the speech becomes. Lower
	// values (like 0.3) create more neutral, consistent speaking styles. Higher values
	// (like 1.0) allow for more dynamic emotional range and speaking styles.
	Temperature param.Opt[float64] `json:"temperature,omitzero"`
	// Controls the stability of the generated speech. A lower value (like 0.3)
	// produces more consistent, reliable speech. A higher value (like 0.9) gives more
	// flexibility in how words are spoken, but might occasionally produce unusual
	// intonations or speech patterns.
	TopP param.Opt[float64] `json:"top_p,omitzero"`
	paramObj
}

func (r SpeechGenerateParams) MarshalJSON() (data []byte, err error) {
	type shadow SpeechGenerateParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *SpeechGenerateParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type SpeechGenerateDetailedParams struct {
	// The text to generate speech from; max 5000 characters per request (including
	// spaces).
	Text string `json:"text" api:"required"`
	// The voice id of the voice to use; voice ids can be retrieved by calls to `List
	// voices` or `Voice info`.
	Voice string `json:"voice" api:"required"`
	// When set to true, the generated speech will also be saved to your [clip
	// library](https://app.lmnt.com/clips) in the LMNT playground.
	Debug param.Opt[bool] `json:"debug,omitzero"`
	// The desired output format of the audio. If you are using a streaming endpoint,
	// you'll generate audio faster by selecting a streamable format since chunks are
	// encoded and returned as they're generated. For non-streamable formats, all
	// speech will be generated before encoding.
	//
	// Streamable formats:
	// - `mp3`: 96kbps MP3 audio.
	// - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
	// - `webm`: WebM format with Opus audio codec.
	// - `pcm_s16le`: PCM signed 16-bit little-endian audio.
	// - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
	//
	// Non-streamable formats:
	// - `aac`: AAC audio codec.
	// - `wav`: 16-bit PCM audio in WAV container.
	Format OutputFormat `json:"format,omitzero"`
	// The desired language. Two letter ISO 639-1 code. Defaults to auto language
	// detection, but specifying the language is recommended for faster generation.
	Language LanguageCode `json:"language,omitzero"`
	// The model to use for speech generation. Learn more about models
	// [here](https://docs.lmnt.com/models/overview).
	Model Model `json:"model,omitzero"`
	// If set as `true`, the response will contain a `timestamps` array describing
	// where each input element falls in the generated audio.
	ReturnTimestamps param.Opt[bool] `json:"return_timestamps,omitzero"`
	// The desired output sample rate in Hz. Defaults to `24000` for all formats except
	// `mulaw` which defaults to `8000`.
	SampleRate SampleRate `json:"sample_rate,omitzero"`
	// Influences how expressive and emotionally varied the speech becomes. Lower
	// values (like 0.3) create more neutral, consistent speaking styles. Higher values
	// (like 1.0) allow for more dynamic emotional range and speaking styles.
	Temperature param.Opt[float64] `json:"temperature,omitzero"`
	// Controls the stability of the generated speech. A lower value (like 0.3)
	// produces more consistent, reliable speech. A higher value (like 0.9) gives more
	// flexibility in how words are spoken, but might occasionally produce unusual
	// intonations or speech patterns.
	TopP param.Opt[float64] `json:"top_p,omitzero"`
	paramObj
}

func (r SpeechGenerateDetailedParams) MarshalJSON() (data []byte, err error) {
	type shadow SpeechGenerateDetailedParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *SpeechGenerateDetailedParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
