// Generated by carbonsteel. DO NOT EDIT.

package lmnt_test

import (
	"context"
	"testing"

	lmnt "github.com/lmnt-com/lmnt-go"
)

func TestSpeechGenerate(t *testing.T) {
	client := mockClient(`{}`)
	_, err := client.Speech.Generate(context.Background(), lmnt.SpeechGenerateParams{Voice: "sample", Text: "sample"})
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}

func TestSpeechGenerateDetailed(t *testing.T) {
	client := mockClient(`{}`)
	_, err := client.Speech.GenerateDetailed(context.Background(), lmnt.SpeechGenerateDetailedParams{Voice: "sample", Text: "sample"})
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}
