// Generated by carbonsteel. DO NOT EDIT.

package lmnt_test

import (
	"context"
	"strings"
	"testing"

	lmnt "github.com/lmnt-com/lmnt-go"
)

func TestVoiceNew(t *testing.T) {
	client := mockClient(`{}`)
	_, err := client.Voice.New(context.Background(), lmnt.VoiceNewParams{Name: "sample", File: strings.NewReader("sample")})
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}

func TestVoiceGet(t *testing.T) {
	client := mockClient(`{}`)
	_, err := client.Voice.Get(context.Background(), "sample")
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}

func TestVoiceUpdate(t *testing.T) {
	client := mockClient(`{}`)
	_, err := client.Voice.Update(context.Background(), "sample", lmnt.VoiceUpdateParams{})
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}

func TestVoiceDelete(t *testing.T) {
	client := mockClient(`{}`)
	_, err := client.Voice.Delete(context.Background(), "sample")
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}

func TestVoiceList(t *testing.T) {
	client := mockClient(`[]`)
	_, err := client.Voice.List(context.Background(), lmnt.VoiceListParams{})
	if err != nil {
		t.Fatalf("err should be nil: %s", err)
	}
}
