// Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml#/paths (tag: voice)

package lmnt

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"slices"

	"github.com/lmnt-com/lmnt-go/v2/internal/apiform"
	"github.com/lmnt-com/lmnt-go/v2/internal/apijson"
	"github.com/lmnt-com/lmnt-go/v2/internal/apiquery"
	"github.com/lmnt-com/lmnt-go/v2/internal/requestconfig"
	"github.com/lmnt-com/lmnt-go/v2/option"
	"github.com/lmnt-com/lmnt-go/v2/packages/param"
	"github.com/lmnt-com/lmnt-go/v2/packages/respjson"
)

// VoiceService contains methods that help with interacting with the lmnt API.
//
// Note, unlike clients, this service does not read variables from the
// environment automatically. You should not instantiate this service directly,
// and instead use the [NewVoiceService] method.
type VoiceService struct {
	Options []option.RequestOption
}

// NewVoiceService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if
// there is one), and before any request-specific options.
func NewVoiceService(opts ...option.RequestOption) (r VoiceService) {
	r = VoiceService{}
	r.Options = opts
	return
}

// Create voice
func (r *VoiceService) New(ctx context.Context, body VoiceNewParams, opts ...option.RequestOption) (res *Voice, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/ai/voice"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return
}

// Retrieve voice
func (r *VoiceService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *Voice, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return
	}
	path := fmt.Sprintf("v1/ai/voice/%s", id)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return
}

// Update voice
func (r *VoiceService) Update(ctx context.Context, id string, body VoiceUpdateParams, opts ...option.RequestOption) (res *VoiceUpdateResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return
	}
	path := fmt.Sprintf("v1/ai/voice/%s", id)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return
}

// Delete voice
func (r *VoiceService) Delete(ctx context.Context, id string, opts ...option.RequestOption) (res *VoiceDeleteResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return
	}
	path := fmt.Sprintf("v1/ai/voice/%s", id)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return
}

// List voices
func (r *VoiceService) List(ctx context.Context, query VoiceListParams, opts ...option.RequestOption) (res *[]Voice, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/ai/voice/list"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return
}

// The owner of this voice.
type VoiceOwner string

const (
	VoiceOwnerSystem VoiceOwner = "system"
	VoiceOwnerMe     VoiceOwner = "me"
	VoiceOwnerOther  VoiceOwner = "other"
)

// The method by which this voice was created. Always `instant`.
type VoiceType string

const (
	VoiceTypeInstant VoiceType = "instant"
)

// Voice details
type Voice struct {
	// The unique identifier of this voice.
	ID string `json:"id" api:"required"`
	// The display name of this voice.
	Name string `json:"name" api:"required"`
	// The owner of this voice.
	Owner VoiceOwner `json:"owner" api:"required"`
	// The state of this voice in the training pipeline (e.g., `ready`, `training`).
	State string `json:"state" api:"required"`
	// A text description of this voice.
	Description string `json:"description" api:"nullable"`
	// A tag describing the gender of this voice, e.g. `male`, `female`, `nonbinary`.
	Gender string `json:"gender"`
	// A URL that returns a preview speech sample of this voice. The file can be played
	// directly in a browser or audio player.
	PreviewURL string `json:"preview_url"`
	// Whether this voice has been starred by you or not.
	Starred bool `json:"starred"`
	// Tags attached to this voice.
	Tags []string `json:"tags"`
	// The method by which this voice was created. Always `instant`.
	Type VoiceType `json:"type"`
	// RequestID is the LMNT request identifier, copied from the `request-id`
	// response header. It is populated on the value returned by an operation;
	// it is empty on structs nested inside that value.
	RequestID string `json:"-"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ID          respjson.Field
		Name        respjson.Field
		Owner       respjson.Field
		State       respjson.Field
		Description respjson.Field
		Gender      respjson.Field
		PreviewURL  respjson.Field
		Starred     respjson.Field
		Tags        respjson.Field
		Type        respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r Voice) RawJSON() string { return r.JSON.raw }
func (r *Voice) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type VoiceUpdateResponse struct {
	// Voice details
	Voice Voice `json:"voice" api:"required"`
	// RequestID is the LMNT request identifier, copied from the `request-id`
	// response header. It is populated on the value returned by an operation;
	// it is empty on structs nested inside that value.
	RequestID string `json:"-"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Voice       respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r VoiceUpdateResponse) RawJSON() string { return r.JSON.raw }
func (r *VoiceUpdateResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type VoiceDeleteResponse struct {
	Success bool `json:"success" api:"required"`
	// RequestID is the LMNT request identifier, copied from the `request-id`
	// response header. It is populated on the value returned by an operation;
	// it is empty on structs nested inside that value.
	RequestID string `json:"-"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Success     respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// Returns the unmodified JSON received from the API
func (r VoiceDeleteResponse) RawJSON() string { return r.JSON.raw }
func (r *VoiceDeleteResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type VoiceNewParams struct {
	// The input audio file to train the voice with, as a binary `wav`, `mp3`, `mp4`,
	// `m4a`, or `webm` attachment.
	// - Max file size: 250 MB.
	File io.Reader `json:"file" api:"required"`
	// The display name for this voice
	Name string `json:"name" api:"required"`
	// A text description of this voice.
	Description param.Opt[string] `json:"description,omitzero"`
	// A tag describing the gender of this voice. Has no effect on voice creation.
	Gender param.Opt[string] `json:"gender,omitzero"`
	// A list of tags to attach to this voice.
	Tags []string `json:"tags,omitzero"`
	paramObj
}

func (r VoiceNewParams) MarshalMultipart() (data []byte, contentType string, err error) {
	buf := bytes.NewBuffer(nil)
	writer := multipart.NewWriter(buf)
	err = apiform.MarshalRoot(r, writer)
	if err == nil {
		err = apiform.WriteExtras(writer, r.ExtraFields())
	}
	if err != nil {
		writer.Close()
		return nil, "", err
	}
	err = writer.Close()
	if err != nil {
		return nil, "", err
	}
	return buf.Bytes(), writer.FormDataContentType(), nil
}

type VoiceUpdateParams struct {
	// A description of this voice.
	Description param.Opt[string] `json:"description,omitzero"`
	// A tag describing the gender of this voice, e.g. `male`, `female`, `nonbinary`.
	Gender param.Opt[string] `json:"gender,omitzero"`
	// The display name for this voice.
	Name param.Opt[string] `json:"name,omitzero"`
	// If `true`, adds this voice to your starred list.
	Starred param.Opt[bool] `json:"starred,omitzero"`
	// Replaces the tags attached to this voice with the given list.
	Tags []string `json:"tags,omitzero"`
	paramObj
}

func (r VoiceUpdateParams) MarshalJSON() (data []byte, err error) {
	type shadow VoiceUpdateParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *VoiceUpdateParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type VoiceListParams struct {
	// Which owner's voices to return. Choose from `system`, `me`, or `all`.
	Owner param.Opt[string] `query:"owner,omitzero" json:"-"`
	// If true, only returns voices that you have starred.
	Starred param.Opt[string] `query:"starred,omitzero" json:"-"`
	paramObj
}

// URLQuery serializes [VoiceListParams]'s query parameters as `url.Values`.
func (r VoiceListParams) URLQuery() (v url.Values, err error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatComma,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}
