// Generated by carbonsteel. DO NOT EDIT.

// Package wsstream is a minimal WebSocket transport for the LMNT SDK's
// streaming session resource. It wraps github.com/coder/websocket behind a
// four-method [Conn] interface so the generated session code can be tested
// against an in-process fake (see [option.WithWSDialer]).
//
// The runtime is deliberately small: message-type dispatch, keepalive, and the
// typed receive-side union all live in the generated session code, not here.
package wsstream

import (
	"bytes"
	"context"
	"net/http"
	"sync"

	"github.com/coder/websocket"
)

// MessageKind distinguishes text and binary WebSocket frames.
type MessageKind int

const (
	MessageText MessageKind = iota + 1
	MessageBinary
)

// Frame is a single WebSocket message read from the connection.
//
// Data is valid only until the next call to [Conn.Read]: the connection reuses
// one buffer across reads. Callers that need the bytes to outlive the next read
// must copy them (`append([]byte(nil), frame.Data...)`).
type Frame struct {
	Kind MessageKind
	Data []byte
}

// Conn is the WebSocket transport interface. The generated session code holds a
// Conn (interface), not a concrete type, so tests can inject a fake via
// [option.WithWSDialer] without constructing a real socket.
type Conn interface {
	// Write sends one frame. Safe for concurrent use; writes are serialized.
	Write(ctx context.Context, kind MessageKind, payload []byte) error
	// Read returns the next frame. Single-reader only.
	Read(ctx context.Context) (Frame, error)
	// Ping sends a WebSocket ping and waits for the pong.
	Ping(ctx context.Context) error
	// Close closes the connection with a normal-closure status.
	Close() error
}

// Dialer opens a WebSocket connection. [Dial] is the production implementation;
// tests supply their own via [option.WithWSDialer].
type Dialer = func(ctx context.Context, url string, headers http.Header) (Conn, error)

const (
	// readBufferSize pre-grows the per-connection read buffer so a typical
	// audio frame is read in a single pass without a grow-and-copy.
	readBufferSize = 8 << 10 // 8 KiB
	// maxFrameBytes bounds a single inbound frame, defending against a
	// misbehaving server pushing an unbounded message and OOM'ing the client.
	maxFrameBytes = 1 << 20 // 1 MiB
)

// Dial opens a WebSocket connection to url, sending headers on the handshake.
// It returns the [Conn] interface (not the concrete type) so the field type in
// generated code is uniform with what fake dialers return.
func Dial(ctx context.Context, url string, headers http.Header) (Conn, error) {
	ws, _, err := websocket.Dial(ctx, url, &websocket.DialOptions{HTTPHeader: headers})
	if err != nil {
		return nil, err
	}
	ws.SetReadLimit(maxFrameBytes)
	c := &wsConn{ws: ws}
	c.readBuf.Grow(readBufferSize)
	return c, nil
}

// wsConn is the production [Conn], backed by github.com/coder/websocket.
type wsConn struct {
	ws      *websocket.Conn
	writeMu sync.Mutex
	readBuf bytes.Buffer // reused across Read calls; pre-grown to readBufferSize
}

func (c *wsConn) Write(ctx context.Context, kind MessageKind, payload []byte) error {
	c.writeMu.Lock()
	defer c.writeMu.Unlock()
	return c.ws.Write(ctx, messageType(kind), payload)
}

func (c *wsConn) Read(ctx context.Context) (Frame, error) {
	// Reader (not Read) lets us stream into the reused buffer rather than
	// allocating a fresh []byte per frame.
	typ, r, err := c.ws.Reader(ctx)
	if err != nil {
		return Frame{}, err
	}
	c.readBuf.Reset()
	if _, err := c.readBuf.ReadFrom(r); err != nil {
		return Frame{}, err
	}
	return Frame{Kind: frameKind(typ), Data: c.readBuf.Bytes()}, nil
}

func (c *wsConn) Ping(ctx context.Context) error { return c.ws.Ping(ctx) }

func (c *wsConn) Close() error {
	return c.ws.Close(websocket.StatusNormalClosure, "")
}

func messageType(k MessageKind) websocket.MessageType {
	if k == MessageBinary {
		return websocket.MessageBinary
	}
	return websocket.MessageText
}

func frameKind(t websocket.MessageType) MessageKind {
	if t == websocket.MessageBinary {
		return MessageBinary
	}
	return MessageText
}

var _ Conn = (*wsConn)(nil)
