// Generated by carbonsteel. DO NOT EDIT.

package wsstream

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/coder/websocket"
)

// TestReadReturnsEOFOnServerNormalClosure verifies that a graceful server-side
// close (status 1000) is surfaced as io.EOF, so the generated session's
// Recv/Messages/StreamAudio loops terminate cleanly instead of propagating the
// raw *websocket.CloseError. The generated session_test.go injects a fake Conn
// via option.WithWSDialer and so never exercises the real wsConn.Read close
// handling — this test covers that gap.
func TestReadReturnsEOFOnServerNormalClosure(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		c, err := websocket.Accept(w, r, nil)
		if err != nil {
			return
		}
		_ = c.Write(r.Context(), websocket.MessageText, []byte("hello"))
		c.Close(websocket.StatusNormalClosure, "")
	}))
	defer srv.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	conn, err := Dial(ctx, "ws"+strings.TrimPrefix(srv.URL, "http"), nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}
	defer conn.Close()

	frame, err := conn.Read(ctx)
	if err != nil {
		t.Fatalf("first read: unexpected error: %v", err)
	}
	if frame.Kind != MessageText || string(frame.Data) != "hello" {
		t.Fatalf("first read: got kind=%d data=%q, want text %q", frame.Kind, frame.Data, "hello")
	}

	if _, err := conn.Read(ctx); !errors.Is(err, io.EOF) {
		t.Fatalf("second read after server normal close: got %v, want io.EOF", err)
	}
}
