// Generated by carbonsteel. DO NOT EDIT. Source: openapi.yaml + asyncapi.yaml

package shared

// ErrorType is the slug identifying an API error category, as carried by the
// `{"error":{"type":...}}` envelope. Returned by [apierror.Error.Type].
type ErrorType string

const (
	ErrorTypeInvalidRequestError  ErrorType = "invalid_request_error"
	ErrorTypeAuthenticationError  ErrorType = "authentication_error"
	ErrorTypePermissionError      ErrorType = "permission_error"
	ErrorTypeNotFoundError        ErrorType = "not_found_error"
	ErrorTypePaymentRequiredError ErrorType = "payment_required_error"
	ErrorTypeRateLimitError       ErrorType = "rate_limit_error"
	ErrorTypeInternalServerError  ErrorType = "internal_server_error"
)

// The desired language. Two letter ISO 639-1 code. Defaults to auto language
// detection, but specifying the language is recommended for faster generation.
type LanguageCode string

const (
	LanguageCodeAuto LanguageCode = "auto"
	LanguageCodeAr   LanguageCode = "ar"
	LanguageCodeAs   LanguageCode = "as"
	LanguageCodeBn   LanguageCode = "bn"
	LanguageCodeCs   LanguageCode = "cs"
	LanguageCodeDa   LanguageCode = "da"
	LanguageCodeDe   LanguageCode = "de"
	LanguageCodeEn   LanguageCode = "en"
	LanguageCodeEs   LanguageCode = "es"
	LanguageCodeFi   LanguageCode = "fi"
	LanguageCodeFr   LanguageCode = "fr"
	LanguageCodeHi   LanguageCode = "hi"
	LanguageCodeID   LanguageCode = "id"
	LanguageCodeIt   LanguageCode = "it"
	LanguageCodeJa   LanguageCode = "ja"
	LanguageCodeKo   LanguageCode = "ko"
	LanguageCodeMl   LanguageCode = "ml"
	LanguageCodeMr   LanguageCode = "mr"
	LanguageCodeNl   LanguageCode = "nl"
	LanguageCodePl   LanguageCode = "pl"
	LanguageCodePt   LanguageCode = "pt"
	LanguageCodeRu   LanguageCode = "ru"
	LanguageCodeSk   LanguageCode = "sk"
	LanguageCodeSv   LanguageCode = "sv"
	LanguageCodeTa   LanguageCode = "ta"
	LanguageCodeTe   LanguageCode = "te"
	LanguageCodeTh   LanguageCode = "th"
	LanguageCodeTr   LanguageCode = "tr"
	LanguageCodeUk   LanguageCode = "uk"
	LanguageCodeUr   LanguageCode = "ur"
	LanguageCodeVi   LanguageCode = "vi"
	LanguageCodeZh   LanguageCode = "zh"
)

// The model to use for speech generation. Learn more about models
// [here](https://docs.lmnt.com/models/overview).
type Model string

const (
	ModelBlizzard Model = "blizzard"
)

// The desired output format of the audio. If you are using a streaming endpoint,
// you'll generate audio faster by selecting a streamable format since chunks are
// encoded and returned as they're generated. For non-streamable formats, all
// speech will be generated before encoding.
//
// Streamable formats:
// - `mp3`: 96kbps MP3 audio.
// - `ulaw`: 8-bit G711 µ-law audio with a WAV header.
// - `webm`: WebM format with Opus audio codec.
// - `pcm_s16le`: PCM signed 16-bit little-endian audio.
// - `pcm_f32le`: PCM 32-bit floating-point little-endian audio.
//
// Non-streamable formats:
// - `aac`: AAC audio codec.
// - `wav`: 16-bit PCM audio in WAV container.
type OutputFormat string

const (
	OutputFormatAAC      OutputFormat = "aac"
	OutputFormatMP3      OutputFormat = "mp3"
	OutputFormatULaw     OutputFormat = "ulaw"
	OutputFormatWav      OutputFormat = "wav"
	OutputFormatWebM     OutputFormat = "webm"
	OutputFormatPCMS16LE OutputFormat = "pcm_s16le"
	OutputFormatPCMF32LE OutputFormat = "pcm_f32le"
)

// The desired output sample rate in Hz. Defaults to `24000` for all formats except
// `mulaw` which defaults to `8000`.
type SampleRate int64

const (
	SampleRate8000  SampleRate = 8000
	SampleRate16000 SampleRate = 16000
	SampleRate24000 SampleRate = 24000
)
